# This is a basic workflow to help you get started with Actions

# name: CD

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3
#       - name: Install Python 3.11.1
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.11.1
      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!
        

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           cd tests
#           pip install pytest
#           pip install pytest-cov
#           python3 start.py -h
#           echo Add other actions to build,
#           echo test, and deploy your project.
      #Runs a help function
#        - name: Run a  help script
#          run: python3 start.py -h
          
name: Run Tests On Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.11.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.1
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt
      #     echo requirements installed
      - name: Run tests
        run: |
          cd tests
          pip install pytest
          pip install pytest-cov
          pytest start.py -h
          
